// FIX: Add React import to resolve TypeScript error 'Cannot find namespace React'.
import React from 'react';
import { AIProvider, AIMode } from './types';
import { ChatIcon, ThinkingIcon, ImageIcon, MapPinIcon, SearchIcon, CameraIcon, LightningIcon, VideoIcon, LocalAIIcon, WandIcon, MicIcon, SparklesIcon } from './components/icons';

export const PROVIDER_MODES: Record<AIProvider, {
    mode: AIMode,
    Icon: React.FC<React.SVGProps<SVGSVGElement>>,
    description: string,
    prompts: string[]
}[]> = {
    [AIProvider.LOCAL_AI]: [
        {
            mode: AIMode.CHAT,
            Icon: ChatIcon,
            description: 'Chat with a privacy-focused AI that runs entirely on your device. Responses are generated by a local model and no data leaves your browser.',
            prompts: [
                'Hello, who are you?',
                'What are your capabilities?',
                'Write a short poem about the ocean.',
                'Explain the concept of a Large Language Model.'
            ]
        }
    ],
    [AIProvider.OLLAMA]: [
        {
            mode: AIMode.CHAT,
            Icon: ChatIcon,
            description: 'Connect to a custom, OpenAI-compatible model running on your local machine. Ideal for Ollama, LM Studio, etc.',
            prompts: [
                'Who are you?',
                'Tell me about the model that you are.',
                'Write a haiku about a local server.',
                'Explain what an API endpoint is.'
            ]
        },
        {
            mode: AIMode.IMAGE_UNDERSTANDING,
            Icon: CameraIcon,
            description: 'Analyze an image with your local model. This requires a multimodal model (e.g., LLaVA) to be running.',
            prompts: [
                'Describe this image in detail.',
                'What is the main subject of this picture?',
                'Is there any text in this image? If so, what does it say?',
            ]
        }
    ],
    [AIProvider.GEMINI]: [
        {
            mode: AIMode.CHAT,
            Icon: ChatIcon,
            description: 'Standard chat mode. Balanced for conversation, summarization, and creative writing tasks.',
            prompts: [
                'Explain quantum computing in simple terms.',
                'Write a short story about a friendly robot who discovers music.',
                'What are three fun things to do in Paris?'
            ]
        },
        {
            mode: AIMode.LIVE_CONVERSATION,
            Icon: MicIcon,
            description: 'Start a real-time voice conversation with Gemini. Uses your microphone for a low-latency, hands-free chat experience.',
            prompts: [
                'Let\'s have a conversation.',
                'Tell me a fun fact.',
                'What\'s the weather like today?',
            ]
        },
        {
            mode: AIMode.THINKING,
            Icon: ThinkingIcon,
            description: 'Uses a more advanced model for complex reasoning, logic, and coding problems.',
            prompts: [
                'Solve this riddle: I have cities, but no houses; forests, but no trees; and water, but no fish. What am I?',
                'Write a python script to sort a list of dictionaries by a specific key.',
                'What are the philosophical implications of artificial intelligence?'
            ]
        },
        {
            mode: AIMode.LOW_LATENCY,
            Icon: LightningIcon,
            description: 'Optimized for speed. Provides the fastest possible responses for quick Q&A and rapid exchanges.',
            prompts: [
                'What is the capital of Australia?',
                'Translate "Hello, how are you?" to Spanish.',
                'Give me a random fact.'
            ]
        },
        {
            mode: AIMode.IMAGE_GEN,
            Icon: ImageIcon,
            description: 'Generate a high-quality image from a text description. Be descriptive for best results.',
            prompts: [
                'A photorealistic image of an astronaut riding a horse on Mars.',
                'A cute, fluffy cat typing on a glowing keyboard, digital art.',
                'A logo for a coffee shop named "The Starship Brew".'
            ]
        },
        {
            mode: AIMode.ARTISTIC_GEN,
            Icon: SparklesIcon,
            description: 'Unleash creative potential. This mode is for artistic, abstract, or less-conventional image concepts, aiming for fewer stylistic restrictions.',
            prompts: [
                'The concept of loneliness, visualized as a surreal landscape.',
                'A clock melting in a desolate, dream-like desert.',
                'Symmetry of chaos, abstract digital art.',
                'A city skyline built from musical instruments.'
            ]
        },
         {
            mode: AIMode.IMAGE_EDITING,
            Icon: WandIcon,
            description: 'Upload an image and edit it with a text prompt. Describe the changes you want to see.',
            prompts: [
                'Add a retro, vintage filter to this image.',
                'Make this look like a watercolor painting.',
                'Change the background to a futuristic city.'
            ]
        },
        {
            mode: AIMode.IMAGE_UNDERSTANDING,
            Icon: CameraIcon,
            description: 'Analyze an uploaded image. Ask questions about the image content, identify objects, or get a description.',
            prompts: [
                'Describe what is happening in this picture.',
                'What is the main color in this image?',
                'Can you identify any landmarks in this photo?'
            ]
        },
        {
            mode: AIMode.VIDEO_UNDERSTANDING,
            Icon: VideoIcon,
            description: 'Analyze an uploaded video. The AI will process frames to understand the content.',
            prompts: [
                'Summarize this video.',
                'What is the primary activity shown in this video?',
                'Describe the setting of this video.'
            ]
        },
        {
            mode: AIMode.SEARCH,
            Icon: SearchIcon,
            description: 'Grounds the response with up-to-date information from Google Search. Ideal for recent events or news.',
            prompts: [
                'Who won the latest Super Bowl?',
                'What are the top news headlines today?',
                'Summarize recent developments in AI.'
            ]
        },
        {
            mode: AIMode.MAPS,
            Icon: MapPinIcon,
            description: 'Grounds the response with Google Maps data. Ask for nearby places or location-based information.',
            prompts: [
                'Find good pizza places near me.',
                'How far is the Eiffel Tower from the Louvre Museum?',
                'Show me pictures of Golden Gate Park.'
            ]
        },
    ],
    [AIProvider.OPENAI]: [
        {
            mode: AIMode.CHAT,
            Icon: ChatIcon,
            description: 'Chat with GPT-4o. A powerful and intelligent conversational model from OpenAI.',
            prompts: [
                'Write a short poem about the moon.',
                'Explain the concept of recursion like I\'m five.',
                'Plan a 3-day trip to Tokyo.'
            ]
        },
        {
            mode: AIMode.IMAGE_GEN,
            Icon: ImageIcon,
            description: 'Generate a high-quality image using DALL-E 3. Be descriptive for best results.',
            prompts: [
                'An oil painting of a robot playing chess in a Parisian cafe.',
                'A cute corgi in a superhero cape, comic book style.',
                '3D render of a futuristic city with flying cars.'
            ]
        },
        {
            mode: AIMode.ARTISTIC_GEN,
            Icon: SparklesIcon,
            description: 'Generate images with more creative freedom using DALL-E 3. Designed for artistic expressions that may be outside the norm.',
            prompts: [
                'A portrait of a person made entirely of swirling galaxies and stardust.',
                'The feeling of "deja vu" represented as an Escher-like impossible staircase.',
                'A biomechanical dragon, fusion of organic and machine parts, hyperrealistic.',
                'Gothic horror depiction of a library where books have come to life.'
            ]
        },
        {
            mode: AIMode.IMAGE_UNDERSTANDING,
            Icon: CameraIcon,
            description: 'Analyze an uploaded image with GPT-4o Vision. Ask questions about the image content.',
            prompts: [
                'What is unusual about this image?',
                'Write a creative story based on this picture.',
                'Can you identify the objects on the table?'
            ]
        }
    ],
    [AIProvider.ANTHROPIC]: [
        {
            mode: AIMode.CHAT,
            Icon: ChatIcon,
            description: 'Chat with Claude 3 Opus. A powerful conversational model from Anthropic, known for its thorough responses.',
            prompts: [
                'Compare and contrast the economic theories of Keynes and Hayek.',
                'Write a sonnet about the feeling of nostalgia.',
                'What are the main ethical considerations for developing advanced AI?'
            ]
        }
    ],
    [AIProvider.COHERE]: [
        {
            mode: AIMode.CHAT,
            Icon: ChatIcon,
            description: 'Chat with Command R+. A powerful conversational model from Cohere, focused on enterprise-grade applications.',
            prompts: [
                'Summarize the following business report for an executive summary.',
                'Draft a professional email to a client regarding a project delay.',
                'Generate a list of FAQs for a new software product.'
            ]
        }
    ],
    [AIProvider.FREE_AI]: [
        {
            mode: AIMode.CHAT,
            Icon: SparklesIcon,
            description: 'Chat with a free, on-device AI model. No API key or internet connection required (after first load). Your data never leaves your computer.',
            prompts: [
                'Hello, who are you?',
                'Write a short poem about privacy.',
                'Tell me a joke.',
                'Explain how a car engine works in simple terms.'
            ]
        }
    ],
    [AIProvider.HUGGING_FACE]: []
};